In [37]:
import numpy as np

In [ ]:
import numpy as np
import time
size=1000_000_000
py_list=list(range(size))
start_time=time.time()
sq_list=[x**2 for x in py_list]
end_time=time.time()
print(f"the time taken by python list={end_time-start_time} seconds")
# numpy array
np_array_list=np.array(py_list)
start_time=time.time()
#vectorization
np_array_list=np_array_list**2
end_time=time.time()

print(f"the time taken by numpy array list={end_time-start_time} seconds")

In [2]:
print("hello")

hello


In [9]:
py_list=[[1,3,0],[2,3,6],[23.8,67,78]]

arr_list=np.array(py_list)
print(arr_list)

[[ 1.   3.   0. ]
 [ 2.   3.   6. ]
 [23.8 67.  78. ]]


In [16]:
arr1=np.zeros((2,3),dtype="int64")
print(arr1,type(arr1),arr1.dtype,arr1.shape)

[[0 0 0]
 [0 0 0]] <class 'numpy.ndarray'> int64 (2, 3)


In [17]:
arr1=np.ones((2,3),dtype="int64")
print(arr1,type(arr1),arr1.dtype,arr1.shape)

[[1 1 1]
 [1 1 1]] <class 'numpy.ndarray'> int64 (2, 3)


In [21]:
arr1=np.full((2,3),100)

print(arr1,type(arr1),arr1.dtype,arr1.shape)

[[100 100 100]
 [100 100 100]] <class 'numpy.ndarray'> int64 (2, 3)


In [23]:
arr1=np.eye((4),dtype="int64")
print(arr1,type(arr1),arr1.dtype,arr1.shape)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] <class 'numpy.ndarray'> int64 (4, 4)


In [26]:
arr5=np.arange(1,10,2) #start , end(exclussive), step
print(arr5, arr5.shape)

[1 3 5 7 9] (5,)


In [28]:
arr6=np.linspace(1,10,5)  # first , last , n
print(arr6, arr6.shape)

[ 1.    3.25  5.5   7.75 10.  ] (5,)


In [45]:
# property

arr=np.array([[1,2],[8,2],[1,9]])

print(arr.shape)
print(arr.dtype)
print(arr.nbytes)
print(arr.size)
print(arr.ndim)
arr=arr.astype(np.float64)
print(arr)
print(arr.dtype)



(3, 2)
int64
48
6
2
[[1. 2.]
 [8. 2.]
 [1. 9.]]
float64


In [46]:
print(arr[0])
arr=arr.astype(np.int64)

[1. 2.]


In [47]:
# Fancy indexing

idx=[0,2]
print(arr[idx])


[[1 2]
 [1 9]]


In [48]:
# boolean indexing

print(arr[arr%2==0])
print(arr[arr%2!=0])
print(arr[arr>2])

[2 8 2]
[1 1 9]
[8 9]


In [53]:
# Sclicing

print(arr,"this is array")
print(arr[0:3])
print(arr[0:3:2]) 


[[1 2]
 [8 2]
 [1 9]] this is array
[[1 2]
 [8 2]
 [1 9]]
[[1 2]
 [1 9]]


In [55]:
# Data type

arr1=np.array([3+5j])
arr2=np.array([-4-6j])
add=(arr1+arr2)
print(add,add.dtype,add.shape)

[-1.-1.j] complex128 (1,)


In [58]:
# if we add heterogenious data in numpy it treat it as a object

arr_list=[{1,2},3,5,6.6]
arr=np.array(arr_list)
print(arr,arr.dtype)
#Yes — in this case NumPy treats the array as object.

[{1, 2} 3 5 6.6] object


In [60]:
# Multi dementional arrays

arr2D=[[4,5,6],[4,5,8],[9,10,4],[1,2,3]]
print(arr2D)
column_by_adding=np.sum(arr2D,axis=0)
print(column_by_adding)
print(np.sum(arr2D))

[[4, 5, 6], [4, 5, 8], [9, 10, 4], [1, 2, 3]]
[18 22 21]
61


In [65]:
# vectorization -->  Vectorization is the process of performing operations on entire NumPy arrays at once without using explicit loops.


arr=[1,2,3,4,5]
arr=np.array(arr)
arr1=arr+10  # --it use broadcasting as [1,2,3,4,5] + [10,10,10,10,10]

arr2=arr*arr
arr3=arr**2
arr4=arr3-arr2
print(arr1,arr2,arr3,arr4)


[11 12 13 14 15] [ 1  4  9 16 25] [ 1  4  9 16 25] [0 0 0 0 0]


In [89]:
# functions 

# Aggregation function --> single output 

arr=np.array([1,2,3,4,4])

print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.prod(arr))
print(np.argmin(arr))  #--> it will provide index of min element

print(np.argmax(arr)) 
print(np.mean(arr))
print(np.std(arr)) #standard deviation
print(np.median(arr)) 
print(np.var(arr)) # variance





14
4
1
96
0
3
2.8
1.16619037896906
3.0
1.3599999999999999


In [90]:
# Power function


print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 16]
[1.         1.41421356 1.73205081 2.         2.        ]
[ 1  8 27 64 64]


In [91]:
# Log function 


print(np.log(arr)) # -->log base e

print(np.log10(arr))

print(np.exp(arr))




[0.         0.69314718 1.09861229 1.38629436 1.38629436]
[0.         0.30103    0.47712125 0.60205999 0.60205999]
[ 2.71828183  7.3890561  20.08553692 54.59815003 54.59815003]


In [92]:
# rounding functions


print(np.round(2.51))

print(np.ceil(2.7))

print(np.floor(2.51))

print(np.trunc(2.7))


print(np.unique(arr))

3.0
3.0
2.0
2.0
[1 2 3 4]
